server.port=8080
#spring.datasource.driver-class-name=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/task_trekker
spring.datasource.username=postgres
spring.datasource.password=222324
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.properties.hibernate.jdbc.time_zone: UTC


security.jwt.secret-key=egor6ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.access-token-expiration-ms=360000